### ISSUE TITLE
AlgReal to Integer

### ISSUE THREAD

**Issue by LeventErkok** [Sheinxy/Advent-Of-Code#2]
Cool solution!

Regarding:

https://github.com/Sheinxy/Advent-Of-Code/blob/9c991586f47c217ce068373186dba7802b00148f/2023/Day_24/Day_24.hs#L60-L61

The proper SBV way of coding this would be:

```haskell
    let s = (x + y + z) :: AlgReal
    case toRational s of
      a :% 1 -> return a
      _      -> error "Not an integer"
```

The above will convert to an `Integer`; you can `fromIntegral` it to get an `Int`. (Which, in general, isn't safe; for obvious reasons.) You'll also need 

```haskell
import GHC.Real(Ratio((:%)))
```
for the above to work.

Why z3 takes much longer for `SInteger` vs `SReal` is a much harder question to answer. I suspect that if you run it on a different input file, the difference may not be that much. Solving these sorts of equations over reals is relatively easy (a variant of gaussian elimination suffices), while over integers it can be much harder. Hard to guess without looking at the internals of the solver itself, which unfortunately is mostly a black-box.

**Comment by Sheinxy** [comment]
Thank you for pointing that out! This is obviously way cleaner than my silly hackaround :D

Considering this is an AOC problem, I am not the most regarding when it comes to safety (I don't want to spend too much time on soving these puzzles, so I am often willing to take shortcuts and go the easy way) so fromIntegral is fine to use in that case in my opinion (I guess I could also simply make my output be an Integer instead. It's definitely safer, so I'll think about it)

As you suspected, running z3 with SInteger vs SReal really depends on the input file. I ran z3 with SIntegers on a friend's input file and it found a solution in about 8s, whereas my input still computes after an hour (unlucky me :,D)


Anyhow, thank you very much for taking your time to share your insights, I greatly appreciate that!
